      - name: Integrasi KernelSU Next
        run: |
          # Menggunakan command manual agar lebih stabil
          git clone https://github.com/rifsxd/KernelSU-Next
          cd KernelSU-Next
          # Menjalankan script setup dari folder hasil clone
          KSU_NEXT_VERSION=$(git describe --abbrev=0 --tags)
          cd ..
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/${KSU_NEXT_VERSION}/kernel/setup.sh" | bash -
          
          # Mengaktifkan config yang dibutuhkan
          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/exynos9810-starlte_defconfig
          echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/exynos9810-starlte_defconfig
          echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/exynos9810-starlte_defconfig

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          # Sesuaikan dengan nama defconfig di repo mrcxlinux
          make O=out exynos9810-starlte_defconfig
          make -j$(nproc) O=out CC=clang

      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-S9-KSU-Next
          path: out/arch/arm64/boot/Image.gz-dtb
          
